(* This file was generated by lv6 version v6.104.0. *)
(*  lv6 -ec -node fulllB -o fullb.ec 1bit.lus *)
(* on EloiUBUNTU the 23/11/2021 at 10:13:32 *)

node fulllB(a:bool) 
returns (b_0:bool; b_1:bool; b_2:bool; b_3:bool; b_4:bool; b_5:bool; b_6:bool; b_7:bool);
let
   b_7 = true;
   b_6 = false;
   b_5 = false;
   b_4 = false;
   b_3 = false;
   b_2 = false;
   b_1 = false;
   b_0 = false;
tel
-- end of node 1bit__fulllB
